services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin
#   mongodb:
#    image: mongo:6-jammy
#    ports:
#      - '27017:27017'
#    networks:
#      - mongo

networks:
  zipkin:
    driver: bridge
#  mongo:
#    driver: bridge
