eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8070

spring:
  application:
    name: schools
  data:
    mongodb:
      uri: mongodb://localhost:27017/schools

application:
  config:
    students-url: http://localhost:8222/api/students

management:
  tracing:
    sampling:
      probability: 1.0