eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8090

spring:
  application:
    name: students
  data:
    mongodb:
      uri: mongodb://localhost:27017/students

management:
  tracing:
    sampling:
      probability: 1.0

